### PR TITLE
2 small fixes regarding gpg

### PR DESCRIPTION
**Pull request by bbinet**
- Add missing import gpg requirement 
- Add missing --homedir option when importing gpg key

### CODE REVIEW

**Comment by fpytloun** [comment]
Thank you :)

**Comment by bbinet** [comment]
@fpytloun FYI, I was not able to use aptly-publisher to publish my mirrors because for some unknown reasons, some packages were not available in the published repository, whereas they were correctly available in the snapshots...
It may be related to the fact that I'm using filtered mirrors...?

Anyway, I gave up with aptly-publisher, since using aptly command line directly was working correctly for me.

**Comment by fpytloun** [comment]
@bbinet publisher publishes only latest snapshots (by name) available for given repository/mirror so it's possible that it published different snapshot than the one you wanted.
I am planning to add some option like `--latest` that would always create snapshots to publish automatically from mirrors/repos.

**Comment by bbinet** [comment]
@fpytloun no it must be an issue with aptly api (which is used by aptly-publisher) I think, because if I publish the same snapshot with the command line, all packages are correctly available...

**Comment by fpytloun** [comment]
It's interesting that I experienced the same issue yesterday. I simply restarted aptly-api and recreated the publish again.

**Pull request merged**
