### PR TITLE
Update aptly_mirror_update.sh

### PR DESCRIPTION
**Pull request by noskovao**
suppress useless output when aptly running in docker container

### CODE REVIEW

**Comment by cloudlab-autobuild** [comment]
Can one of the admins verify this patch?

**Comment by epcim** [comment]
I don't see any reason why it would not work in container.

```
 * [xenial-security-universe]: http://in.archive.ubuntu.com/ubuntu/ xenial-security [src]
 * [xenial-universe]: http://in.archive.ubuntu.com/ubuntu/ xenial [src]
 * [xenial-updates-main]: http://in.archive.ubuntu.com/ubuntu/ xenial-updates [src]
 * [xenial-updates-multiverse]: http://in.archive.ubuntu.com/ubuntu/ xenial-updates [src]
 * [xenial-updates-restricted]: http://in.archive.ubuntu.com/ubuntu/ xenial-updates [src]
 * [xenial-updates-universe]: http://in.archive.ubuntu.com/ubuntu/ xenial-updates [src]

To get more information about mirror, run `aptly mirror show <name>`.
root@c3b118aa603e:/srv/volumes/aptly# aptly mirror list -raw
ceph-mirantis-xenial
ceph-trusty
ceph-xenial
decapod-ceph-mirantis-xenial
glusterfs_upstream_trusty
glusterfs_upstream_trusty_3_8
```

**Comment by epcim** [comment]
I don't see any reason why it would not work in container.

```
 * [xenial-security-universe]: http://in.archive.ubuntu.com/ubuntu/ xenial-security [src]
 * [xenial-universe]: http://in.archive.ubuntu.com/ubuntu/ xenial [src]
 * [xenial-updates-main]: http://in.archive.ubuntu.com/ubuntu/ xenial-updates [src]
 * [xenial-updates-multiverse]: http://in.archive.ubuntu.com/ubuntu/ xenial-updates [src]
 * [xenial-updates-restricted]: http://in.archive.ubuntu.com/ubuntu/ xenial-updates [src]
 * [xenial-updates-universe]: http://in.archive.ubuntu.com/ubuntu/ xenial-updates [src]

To get more information about mirror, run `aptly mirror show <name>`.
root@c3b118aa603e:/srv/volumes/aptly# aptly mirror list -raw
ceph-mirantis-xenial
ceph-trusty
ceph-xenial
decapod-ceph-mirantis-xenial
glusterfs_upstream_trusty
glusterfs_upstream_trusty_3_8
```

**Comment by noskovao** [comment]
Try it outside container.

**Pull request merged**
